apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tom-app
      version: 9
  template:
    metadata:
      name: tom-app
      labels:
        app: tom-app
        version: 9
    spec:
      containers:
      - name: tomcat-container
        image: image-registry.openshift-image-registry.svc:5000/tomcat:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata: 
  name: tom-svc
spec: 
  ports: 
    - 
      name: porttom
      port: 8070
      protocol: TCP
      targetPort: 8080

  selector: 
    app: tom-app
